import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

export default function Layout({ children, pageTitle }) {
  const defaultTitle = "My Flower App";

  return (
    <>
      <Head>
        <title>
          {pageTitle ? `${pageTitle} - ${defaultTitle}` : defaultTitle}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/flower.png" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
